version: '3'

services:

    jones-api:
        image: h4ad/sentry-discord
        container_name: jones_sentry_discord
        environment:
            NODE_ENV: 'development'
            API_BASE_PATH: 'prod'
            PORT: 3000
            API_PORT: 3000
            SWAGGER_TITLE: 'Jones'
            SWAGGER_DESCRIPTION: 'Uma API hospedada com o Docker para a atividade prática do Jones'
            SWAGGER_VERSION: '1.0'
            SWAGGER_TAG: 'Jones'
            SWAGGER_ENABLED: 'true'
            DISCORD_WEBHOOK_URL: 'http://127.0.0.1'
            API_KEY: 'Some Secret Key'
        ports:
            - 3000:3000
        restart: unless-stopped